db.uio.url=jdbc:sqlserver://localhost:1433;databaseName=UIO
db.uio.user=sa
db.uio.password=P@ssw0rd

db.gye.url=jdbc:sqlserver://localhost:1433;databaseName=GYE
db.gye.user=sa
db.gye.password=P@ssw0rd

# Configuración por defecto
default.sucursal=UIO

